
package es.gob.csvbroker.consumer.ws.model;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.0
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "errorInfo", targetNamespace = "urn:es:gob:aapp:csvbroker:webservices:validation:model:v1.0")
public class CSVValidationException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private Object faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public CSVValidationException_Exception(String message, Object faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public CSVValidationException_Exception(String message, Object faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: java.lang.Object
     */
    public Object getFaultInfo() {
        return faultInfo;
    }

}
