
package es.gob.csvbroker.consumer.ws.model;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.0
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CSVValidationCertificateService", targetNamespace = "urn:es:gob:aapp:csvbroker:webservices:validation:v1.0")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CSVValidationCertificateService {


    /**
     * 
     * @param validationRequest
     * @return
     *     returns es.gob.csvbroker.consumer.ws.model.CSVValidationResponse
     * @throws CSVValidationException_Exception
     */
    @WebMethod(action = "urn:csvValidation")
    @WebResult(name = "CSVValidationResponse", targetNamespace = "urn:es:gob:aapp:csvbroker:webservices:validation:model:v1.0")
    @RequestWrapper(localName = "csvValidation", targetNamespace = "urn:es:gob:aapp:csvbroker:webservices:validation:v1.0", className = "es.gob.csvbroker.consumer.ws.model.CsvValidation")
    @ResponseWrapper(localName = "csvValidationResponse", targetNamespace = "urn:es:gob:aapp:csvbroker:webservices:validation:v1.0", className = "es.gob.csvbroker.consumer.ws.model.CsvValidationResponse")
    public CSVValidationResponse csvValidation(
        @WebParam(name = "validationRequest", targetNamespace = "")
        CSVValidationRequest validationRequest)
        throws CSVValidationException_Exception
    ;

    /**
     * 
     * @param validationSecurityRequest
     * @return
     *     returns es.gob.csvbroker.consumer.ws.model.CSVValidationSecurityResponse
     * @throws CSVValidationException_Exception
     */
    @WebMethod(action = "urn:csvValidationSecurity")
    @WebResult(name = "CSVValidationSecurityResponse", targetNamespace = "urn:es:gob:aapp:csvbroker:webservices:validation:model:v1.0")
    @RequestWrapper(localName = "csvValidationSecurity", targetNamespace = "urn:es:gob:aapp:csvbroker:webservices:validation:v1.0", className = "es.gob.csvbroker.consumer.ws.model.CsvValidationSecurity")
    @ResponseWrapper(localName = "csvValidationSecurityResponse", targetNamespace = "urn:es:gob:aapp:csvbroker:webservices:validation:v1.0", className = "es.gob.csvbroker.consumer.ws.model.CsvValidationSecurityResponse")
    public CSVValidationSecurityResponse csvValidationSecurity(
        @WebParam(name = "validationSecurityRequest", targetNamespace = "")
        CSVValidationSecurityRequest validationSecurityRequest)
        throws CSVValidationException_Exception
    ;

}
